using System;
using Windows.Win32;
using Windows.Win32.Foundation;
using Windows.Win32.UI.WindowsAndMessaging;
using Windows.Win32.UI.Input.KeyboardAndMouse;

namespace keyboardmouse.input;

/// <summary>
/// Registers a global hotkey and runs a simple message loop, invoking a callback when the hotkey fires.
/// Disposes by unregistering the hotkey.
/// </summary>
internal sealed class HotKeyListener : IDisposable
{
    // WM_HOTKEY is not generated by CsWin32, so define it manually.
    private const int WM_HOTKEY = 0x0312;

    readonly int _id;
    readonly uint _vk;
    readonly HOT_KEY_MODIFIERS _modifiers;

    public HotKeyListener(int id, uint vk, HOT_KEY_MODIFIERS modifiers = (HOT_KEY_MODIFIERS)0)
    {
        _id = id;
        _vk = vk;
        _modifiers = modifiers;
        PInvoke.RegisterHotKey(HWND.Null, _id, _modifiers, _vk);
    }

    public void RunMessageLoop(Action onHotkey)
    {
        while (PInvoke.GetMessage(out MSG msg, HWND.Null, 0, 0))
        {
            if (msg.message == WM_HOTKEY && msg.wParam == (UIntPtr)_id)
                onHotkey();

            PInvoke.TranslateMessage(in msg);
            PInvoke.DispatchMessage(in msg);
        }
    }

    public void Dispose()
    {
        PInvoke.UnregisterHotKey(HWND.Null, _id);
    }
}
