using keyboardmouse.forms;

namespace keyboardmouse;

static class Program
{
    const int HOTKEY_ID = 1;
    // VK_F8 is not generated by CsWin32; hand-defined here.
    const uint VK_F8 = 0x77;

    [STAThread]
    static void Main()
    {
        OverlayWindow.RegisterWindowClass();

        var navigator = new GridNavigator();
        var overlay = new OverlayWindow();

        try
        {
            overlay.Create();
            navigator.OnBoundsChanged = overlay.UpdateBounds;

            using var input = new GridInputHandler(navigator.Execute);
            using var hook = new KeyboardHook();
            using var hotkey = new HotKeyListener(HOTKEY_ID, VK_F8);

            hotkey.RunMessageLoop(() =>
            {
                if (navigator.IsActive)
                {
                    navigator.Deactivate();
                    input.Reset();
                    hook.Uninstall();
                    overlay.Hide();
                }
                else
                {
                    navigator.Activate();
                    hook.Install(input.HandleKey);
                    overlay.Show();
                }
            });
        }
        finally
        {
            overlay.Destroy();
        }
    }
}
